### ISSUE TITLE
search field

### ISSUE THREAD

**Issue by cspaier** [thosgood/maths-dictionary#24]
Having a search field somewhere to easily look for specific terms could be an enhancement.
Would you welcome such a PR?

**Comment by thosgood** [comment]
at the moment I'm just suggesting to ctrl+f for any specific terms, but if you fancy implementing such a thing then I'd be more than happy!

**Comment by cspaier** [comment]
crtl+f makes sense. When simple things works, why bother?

> you fancy implementing such a thing then I'd be more than happy

Cool. So I started looking at your js and find such:

https://github.com/thosgood/maths-dictionary/blob/ca37970fbb40d6bf9a87754a06cda77abeea9b6e/website/display_dictionary.js#L161-L162

https://github.com/thosgood/maths-dictionary/blob/ca37970fbb40d6bf9a87754a06cda77abeea9b6e/website/display_dictionary.js#L167-L171

So I wonder: Have you consider using [datatable](https://datatables.net/)?

I think with very few work we could fix those issues and have a search field.

If you ok with the idea, I could submit a PR so you see how it would look like.

**Comment by thosgood** [comment]
this seems like a very useful library 🙂 if you submit a PR then I'll definitely have a look at it.
the key thing is to be able to toggle hidden columns (as currently implemented by the "language selector" checkboxes)

**Comment by cspaier** [comment]
All right. I indeed noticed two "specials" behaviours that should be covered by datatable's api:
1. toggle language columns: https://datatables.net/examples/api/show_hide.html
2. Sub rows for `adjs`: https://datatables.net/examples/api/row_details.html

I ll work on that.

**Comment by thosgood** [comment]
sounds amazing! thanks!
