### ISSUE TITLE
Representing compound words

### ISSUE THREAD

**Issue by fingolfin** [thosgood/maths-dictionary#33]
In German, often words are combined to form new words. As a result, the translation of "Fourier series" is "Fourierreihe" (and *not* "Fourier Reihe"). For "power series" it is "Potenzreihe" (and "Potenz Reihe" would be *really* strange to read).

Is there a way to specify this yet? If not, perhaps one could be added?

**Comment by fingolfin** [comment]
There are also examples where it is possible to use an "adjective noun" combo, but it is unusual and the compound would be preferable: e.g. "diagonal matrix" could be translated as "diagonale Matrix", but this would be odd, the usual translation is "Diagonalmatrix".

**Comment by fingolfin** [comment]
Here's another complication: "value" is "Wert" in German. But "absolute value" is "Betrag", or sometimes "Absolutbetrag", but never "absoluter Wert" or anything else involving "Wert".

**Comment by thosgood** [comment]
Great questions, and first of all thank you for your interest in contributing!

As for an actual answer, it basically boils down to "with how poorly the database is currently structured, this is impossible" *but* I'm hoping to get do a complete restructure over the next week or so (if I find the time) which would solve this issue entirely — I'll post on this thread when that's done!

**Comment by thosgood** [comment]
OK, it turned out to be a lot easier than I thought to make a temporary fix: for now, there is no distinction between adjectives and nouns; e.g. the term "diagonal matrix" is simply its own entry, separate from "matrix". This should solve this problem.

**Comment by fingolfin** [comment]
Oh, that's great!

Unfortunately it also means I have to redo this PR I was preparing to add a bunch of German translation... :-(. But I'll manage, no worries ;-)
