### ISSUE TITLE
Dealing with words with multiple meanings

### ISSUE THREAD

**Issue by fingolfin** [thosgood/maths-dictionary#34]
In math, a "lattice" can refer to (at least) two completely different concepts (think "subgroup lattice" versus "$\mathbb{Z}^n$ is a lattice in $\mathbb{R}^n$"). In German, these two concepts have different words ("Verband" and "Gitter").

Can this be handled by your setup? How would I enter it?

**Comment by thosgood** [comment]
the way this is handled is that every concept corresponds exactly to an entry on wikidata (almost always, modulo a few edge cases, and these will eventually have wikidata tags too), so for example lattice in the former sense is [Q595364](https://www.wikidata.org/wiki/Q595364) and in the latter sense it is [Q1096885](https://www.wikidata.org/wiki/Q1096885) — the fact that they happen to have the same translation into English is then something that the database doesn't care about :-)

**Comment by thosgood** [comment]
however, at the moment there is no entry for lattice in either sense, and there is no way for users to add entries via the submission tool, but I'm hoping to do a massive restructure of the entire project soon (see the comments that I'm just about to write on https://github.com/thosgood/maths-dictionary/issues/33) that will fix this
