### ISSUE TITLE
Difficulty translating "adjoint"

### ISSUE THREAD

**Issue by fingolfin** [thosgood/maths-dictionary#40]
The entry for "adjoint" references https://www.wikidata.org/wiki/Q357858 from which I conclude that this meant in the sense of "(left/right) adjoint functor".

But I actually have never seen the word "adjoint" as a free standing noun -- I am familiar with "left/right adjoint functor" or even "left/right adjoint", but not "adjoint" in isolation -- and this leads to a problem in translation, too: I can translate the latter as "links-/rechtsadjungierter Funktor" (noun decorated with an adjective). If I really stretch it perhaps even "Links-/Rechtsadjunigerte(r)" (though I've never heard that being used, and I am not even sure which gender to assign; though I note that category theory is not my speciality, so who knows, perhaps it exists among experts; I'll ask some colleagues next week). But "Adjungierte" alone can not be used in this way, it means something else.

There is also the term ["Adjunktion"](https://de.wikipedia.org/wiki/Adjunktion_(Kategorientheorie)) whose German Wikipedia page is linked to that of the English Wikipedia page for [Adjoint functors](https://en.wikipedia.org/wiki/Adjoint_functors). But it really correspond to the english term "adjunction" (as the similarity already suggests). 

I'd also like to point out that there are other meanings of "adjoint" in math (e.g. "adjoint representation", "adjoint matrix").

So I am at a loss how to proceed there...

One solution would be to change the entry to "adjoint functor" (and then match that in the translations). Or, even to split it into two entries, "left adjoint functor" and "right adjoint functor" (as I am guessing in practice that's what people will want to have translated?). Or one could have three entries, I guess?

**Comment by thosgood** [comment]
Oh this is an interesting one, thanks for catching this. I think I agree with your last suggestion: add two new entries (left and right adjoint functors, respectively) but keep the current one — I'm guessing that this might happen every now and then, that some language just doesn't have a common way of expressing something that others do, so I'm happy to accept that and just show as many translations as we can!

**Comment by thosgood** [comment]
I added left and right adjoint, so this specific instance of the problem is at least partially resolved!
